### ISSUE TITLE
Attachment blocked on smartphones!

### ISSUE THREAD

**Issue by robodyne-robotics** [bluetiger9/SmtpClient-for-Qt#103]
I'm successfully using this library to send emails to my users by adding a PDF file as attachment. All the users can correctly download the attachments sent by my QT application if they read their mails from their web mail (browser) or from their mail client installed on their laptop. However, some of them are not able to download the attached file if they try to read the email from their smartphone (it happens mostly with iphone). The mail reports an attached file, but then it is not clickable. If they try to read the same mail from a laptop, then the attached file is downloadable. Has anyone experienced the same issue? I'm struggling to find a solution with no success. I think it should be related to some safety check by the mail server. Obviously, they can correctly read attached files if I send the email from my webmail instead of my QT application so there must be a problem with the method used by the library to send the attachments. I hope you can supporto me on this! Thank you!

```
SmtpClient smtp("smtp.gmail.com", 465, SmtpClient::SslConnection);
..
smtp.connectToHost();
smtp.login();
smtp.sendMail(message);
```

**Comment by bluetiger9** [comment]
Email attachments are stored on the servers of the recipient's mail provider. Normally, it should have nothing to do with how you send those emails.

Maybe, there is a problem with the Mobile client, or it just tries to prevent you download the attachments for whatever reason.

Btw, what is your Mail provider and what Mobile client are you using?

**Comment by robodyne-robotics** [comment]
the mail provider is gmail and the problem occurs most of the times on iphones (I do not know the name of the standard app used to download emails on IOS), Android users have almost no problems with it.
However, ALL the users can correctly download the attachment from webmail or their laptops.

This is the code I use:
```

 SmtpClient smtp("smtp.gmail.com", 587, SmtpClient::TlsConnection);
        smtp.setUser("email@gmail.com");
        smtp.setPassword("passwd");

        MimeMessage message;
        EmailAddress sender("email@gmail.com", "Palestra PUMP");
        message.setSender(&sender);

        EmailAddress to(email_recipient, ui->listautenti->currentText());
        message.addRecipient(&to);

        message.setSubject("La tua tabella di allenamento!");

        // Add some text
        MimeText text;
        QString testo_della_mail = "Ciao " + nome_utente + ",\n\nin allegato, trovi la tua tabella di allenamento.\n\n\n\n\nA presto, la tua palestra PUMP!\n\n\n\n\n\n\n\n\n\n\nIn ottemperanza al D.lgs. 196/03 e al Regolamento UE 2016/679 in materia di protezione dei dati personali, le informazioni ivi contenute hanno natura strettamente personale e sono indirizzate esclusivamente al destinatario indicato. Qualora abbia ricevuto questa e-mail per errore, La invito cortesemente ad avvertire immediatamente il mittente e a distruggere il presente messaggio.";
        text.setText(testo_della_mail);
        message.addPart(&text);

        // Now we create the attachment object
        MimeAttachment attachment (new QFile(pdf_filename));
        qDebug() << "Filename: " << pdf_filename;

        // the file type can be setted. (by default is application/octet-stream)
        attachment.setContentType("application/pdf");

        // Now add it to message
        message.addPart(&attachment);
       smtp.connectToHost();
        smtp.login();
     smtp.sendMail(message);
smtp.quit();
```
