### ISSUE TITLE
with such error described below

### ISSUE THREAD

**Issue by egger-meow** [bluetiger9/SmtpClient-for-Qt#107]

**Comment by egger-meow** [comment]
undefined reference to '__IMP__ZN8MINETEXT.....
undefined reference to '__IMP__ZN8MINETEXT.....
undefined reference to '__IMP__ZN11MINETEXT.....
undefined reference to '__IMP__ZN10MINETEXT.....
.
.
.
.
.
<img width="531" alt="Screenshot 2022-01-05 052732" src="https://user-images.githubusercontent.com/78677475/148126188-7410118e-66d5-40dc-8ba6-30d41aff6679.png">

**Comment by egger-meow** [comment]
help me!!!

**Comment by azizgarba** [comment]
you need to include SmtpMime   
#include<SmtpMime>

**Comment by bluetiger9** [comment]
I would suggest to check your `#includes` are there. Also don't forget to add the library as compile / link dependency.
