### ISSUE TITLE
Spam Issue

### ISSUE THREAD

**Issue by daipol50** [bluetiger9/SmtpClient-for-Qt#109]
My messages keep going to spam I need help to promote my business my messages keeps going to spam I need help please🙏🙏🙏

**Comment by bluetiger9** [comment]
@daipol50, this is unfortunate, but I doubt this has anything to do with the SMTP Client.

I would suggest you to try talking to your *(and the recipient's)* email provider about the issue. If you're sending emails to a large group of users, you may also want to try a specialized service like SendGrid.
