### ISSUE TITLE
Cannot link this library for macOS

### ISSUE THREAD

**Issue by alexqtc** [bluetiger9/SmtpClient-for-Qt#111]
I used your demo1 project from examples. 
Built it for macOS. However I couldn't run the demo1 application.

`dyld: Library not loaded: libSMTPEmail.1.dylib
Reason: image not found
Abort trap: 6`

Did you check your library for macOS? And what can I do instead of including source code files of this library to my project?

**Comment by alexqtc** [comment]
Hi. Please answer me

**Comment by bluetiger9** [comment]
Never tried to build the library on MacOS...

Have you managed to build the main (shared library) project successfully? This should produce a shared library (.so, or may be .dylib on MacOS). This is then linked to the demo apps.

**Comment by alexqtc** [comment]
Thank you very much for your answer.

Yes, I built the library code for macOS and can see .dylib. However I couldnt find a way how to link this library to demo1 app. 
I mean It builds but when I trying run the application the application cannot find this library in runtime.
At the moment, the only working solution is to include the sources of this library in the project. But it seems to me that this is a dirty solution.

**Comment by bluetiger9** [comment]
The library should be picked up from the location defined in `demo1.pro`: 
https://github.com/bluetiger9/SmtpClient-for-Qt/blob/v1.1/demos/demo1/demo1.pro

Looking at it, I'm not sure if the library setting are picked up on MacOS.

I would try adding after the `else:unix:` part:
```
else:macx: LIBS += -L$$SMTP_LIBRARY_LOCATION -lSMTPEmail
```

Let me know if this works!

**Comment by dgestep** [comment]
For other Qt projects where I've supported Windows, Mac, and Linux, it's this:

Windows uses win32
Linux uses unix
Mac uses linux

So, for your Mac, would need to add an additional else that says:

else:linux:  LIBS += -L$$SMTP_LIBRARY_LOCATION -lSmtpMime

Something like that.
