### ISSUE TITLE
smpclient.cpp append function

### ISSUE THREAD

**Issue by Nelson-Waffo** [bluetiger9/SmtpClient-for-Qt#112]
Hi,

the parameters of append() function of the QByteArray() class are incorrect: "error: no matching function for call to append"

**Comment by Mourad-NOUAILI** [comment]
I have the same issue.

**Comment by bluetiger9** [comment]
This is caused by an `.append()` method removed in Qt6. I fixed it now for v2.0 *(`dev` branch)*.
