### ISSUE TITLE
Failed to connect, causes program to crash (actually attachments cause the problem)

### ISSUE THREAD

**Issue by TheCentroid** [bluetiger9/SmtpClient-for-Qt#113]
I have been trying to use your library in a project that I have been developing. I was basing my code on your Demo3 program. I accidently connected to the wrong port of the mail server and after a few minutes when the connection timed out, it correctly went to the "Failed to connect" step but also produced a 'pure virtual method called' exception. This crashed my program. 

Altering Demo3 to have the same error in the port number produced a similar result but also additionally reported a 'terminate called without an active exception' error.

As our customers will need to set up the connection parameters themselves, we will need to be able to prevent the program from crashing if they get the details wrong, as I did.

Thank you for developing this library which, this issue aside, has proven to be very useful

**Comment by TheCentroid** [comment]
Hi. A but more testing has shown that this is not actually an issue when the system fails to connect but occurs when their is an attachment. The email actually gets sent properly but the program will exit afterwards regardless.

**Comment by TheCentroid** [comment]
The problem seems to be that in the module MimeFile , in its destructor you delete the variable file. This however is a pointer and hence does not need to be deleted and causes the issues I have raised.

**Comment by bluetiger9** [comment]
Fixed this on the `dev` branch.
