### ISSUE TITLE
sendMail not working! help

### ISSUE THREAD

**Issue by bugaenko-cyber** [bluetiger9/SmtpClient-for-Qt#116]
Qt 5.15.2 MinGw 8.1 32-bit

..........
[Socket] OUT: "\r\n."
[Socket] IN:  "554-Transaction failed\r\n"
[Socket] IN:  "554-Reject due to policy restrictions.\r\n"
[Socket] IN:  "554 For explanation visit https://www.ionos.com/help/index.php?id=2425&c=hd\r\n"
SMTP - Failed to send mail!
[SmtpClient] State: DisconnectingState
[Socket] OUT: "QUIT"

passed the connection
login passes
crashes while sending a message

and the server works with other programs 100%.
I'm using a TLS connection.

what's wrong ?

**Comment by bluetiger9** [comment]
Looks like the SMTP server is rejecting your email, because of some policy restrictions.

The link from the error message suggest you should contact them:
> **554 Reject due to policy restrictions**
>
> **Problem**:
> The email was rejected as it violates IONOS policy. The sending server is mostly sending spam messages.
>
> **Solution**:
> Contact us [IONOS](https://postmaster-contact.ionos.com/?&utm_source=helpcenter&utm_medium=knowledge&utm_campaign=2425&utm_term=postmaster-contact&utm_content=deeplink&skipIntcpts=true) to have the facts of the case examined.

**Comment by bugaenko-cyber** [comment]
but still it is not so!

in c# using the MimeKit library everything works with the same parameters

I mean, it's in the code, it happened when the server started using tls

**Comment by bluetiger9** [comment]
@bugaenko-cyber, from the error message it is pretty hard to tell why the IONOS mail server is rejecting the email. Looks like you already have the full SMTP transcript in the logs. I think you should use this logs to ask IONOS about the exact rejection reason.

**Comment by bugaenko-cyber** [comment]
I'll look now and let you know

**Comment by bugaenko-cyber** [comment]
I'll look now and let you know

**Comment by bugaenko-cyber** [comment]
By the way !
will not work at all without this, since 5.15.2 there is no support for QStringEncoder
MimePart::writeContent(device, \\\*QStringEncoder(this->cCharset.toStdString().c_str()).encode(text)\*\\text.toUtf8());

maybe it's because of this

ps while the logs on the server are not available (
