### ISSUE TITLE
QSslSocket Error message on Ubuntu

### ISSUE THREAD

**Issue by MagicMosaic** [bluetiger9/SmtpClient-for-Qt#120]
Hello, I have this error message:

QObject::connect: No such signal QSslSocket::errorOccurred(QAbstractSocket::SocketError)
Failed to login!

Could you help ?
thx

**Comment by HiroProtagonist7777** [comment]
Hi,
i have the same issue. I think this occurred, because the Signal errorOccurred was introduced in Qt 5.15. Do you use a Version lower 5.15?

**Comment by bluetiger9** [comment]
@MagicMosaic, as @HiroProtagonist7777 suggested, please use Qt `>=5.15`! Thanks
