### ISSUE TITLE
Issue with Android

### ISSUE THREAD

**Issue by fdmsiv** [bluetiger9/SmtpClient-for-Qt#121]
I have compiled with Qt6 and run on Windows10 Desktop and on Android Emulator, both send emails as expected.  

When I try to deploy same code to physical Android Device I cannot connect to host (gmail) and I get an error along the lines of "can't wait for byteswritten cause socket is unconnected"

**Comment by bluetiger9** [comment]
@fdmsiv, unfortunately I don't have any experience with Qt on Android. As an investigation step, I would suggest creating a simple application, which just uses a `QSslSocket` to check if a connection to the SMTP server can be established. If that does not works you probably have an issue with the Qt install on Android _(maybe missing shared libs)_. If it works, I would suggest enabling `qDebug()` logs to see what goes wrong.
