### ISSUE TITLE
Client Crashes on text.setText

### ISSUE THREAD

**Issue by joshorenberg** [bluetiger9/SmtpClient-for-Qt#123]
Hi the client is crashing for me on the step text.setText(**string**); Application output says:
Critical error detected c0000374

Here is a backtrace:
![backtrace bt](https://user-images.githubusercontent.com/22732423/186064385-e532fe76-1fa6-4e34-9d9c-4d2ad77acf1f.png)

Here is the code as borrowed from the example:

```
        MimeMessage message;
        EmailAddress sender("sample@sample.com", "sample program");
        message.setSender(sender);

        EmailAddress to(iterator.key(), "");
        message.addRecipient(to);

        message.setSubject("Subject");

        MimeText text;
        text.setText("Hi,\nThis is a simple email message.\n");
        message.addPart(&text);
```

I am running Qt Creator based on Qt 5.15.2. Thanks!

**Comment by ghorwin** [comment]
Note, `addPart()` transfers ownership (should be documented!). You mustn't do this with stack variables. Use:

```c++
MimeText * text = new MimeText;
...
message.addPart(text);
```

**Comment by bluetiger9** [comment]
@ghorwin, `addPart()` does not actually takes ownership of part you're adding. It just expects a `MimePart *` pointer, and the object must remain valid unit you call the `sendMail()` method. This works with stack variables too, as long you're calling the `sendMail()` within the same method. Thanks!
