### ISSUE TITLE
Gmail message truncated

### ISSUE THREAD

**Issue by piervalli** [bluetiger9/SmtpClient-for-Qt#124]
Hi,

I have test the SmtClient with example "Demo2" with tag 1.1. The message is very short a "Hello world". It sent correctly, gmail show all message. Instead when send it with new api 2.2, gmail shows "message truncated". Have a suggestion?

Thanks
Pier

**Comment by piervalli** [comment]
Hi in the versione 2.2
 in the body it adds  the bom
=EF=BB=BF<html><body><h1>This is my first transactional email</h1><img =

instead in the 1.1 we have only
<html><body><h1>This is my first transactional email</h1><img =

I checked in debug

Qt 5.15.2
Original Part
void MimeText::writeContent(QIODevice &device) const {
MimePart::writeContent(device, QTextEncoder(QTextCodec::codecForName(this->cCharset.toStdString().c_str())).fromUnicode(text));
}
This works
MimePart::writeContent(device, text.toUtf8());

**Comment by bluetiger9** [comment]
I think this should be already fixed.
