### ISSUE TITLE
Sending E-Mail without prior authentication

### ISSUE THREAD

**Issue by PidsoEST** [bluetiger9/SmtpClient-for-Qt#127]
Is it possible to send a mail through an smtp server that does not require authentication? Could you provide an example on how this could be accomplished with this library?

Thanks!
Best Regards,

**Comment by attila-tokes** [comment]
Hi @PidsoEST,

Just skip the `.login()` and `.waitForAuthenticated()` steps:
```cpp
    smtp.login("your_email_address@host.com", "your_password");
    if (!smtp.waitForAuthenticated()) {
        qDebug() << "Failed to login!";
        return -2;
    }
```

I think it should work.

Thanks!

**Comment by PidsoEST** [comment]
@attila-tokes Hi! Thanks for your quick reply!

Hmm... I tried applying your suggestions to the demo1 code but I do not receive any mails, even upon double-checking the server IP and port as well as receiver address. The program though seems to run through. I will try to debug it a little to see if something aborts silently somewhere. 

If you have any ideas how to get it to work, I'd be glad!

Best Regards,
