### ISSUE TITLE
TLS with STARTTLS does not get connection

### ISSUE THREAD

**Issue by ghorwin** [bluetiger9/SmtpClient-for-Qt#128]
Example code below does not get to ready-connected:

```c++
	SmtpClient smtp("mail.gmx.net", 587, SmtpClient::TlsConnection);
	smtp.setName("client.localhost");
	smtp.connectToHost();
	if (!smtp.waitForReadyConnected(3000)) {
		qDebug() << "Not connected";
		return;
	}
```

Output:

```
smtpclient: State: ConnectingState
smtpclient: [Socket] State: QAbstractSocket::HostLookupState
smtpclient: [Socket] State: QAbstractSocket::ConnectingState
smtpclient: [Socket] State: QAbstractSocket::ConnectedState
smtpclient: State: ConnectedState
smtpclient: [Socket] IN:  "220 gmx.net (mrgmx005) Nemesis ESMTP Service ready\r\n"
smtpclient: State: _EHLO_State
smtpclient: [Socket] OUT: "EHLO client.localhost"
```

After sending EHLO nothing happens and I get a timeout.

I've tried with another SMTP server, but also after sending EHLO nothing happens (no further state changes until time out). The happens on Windows 10 and Linux (Ubuntu 22.04).

Any ideas how to debug this?

-Andreas

**Comment by cheicktra2** [comment]
hello, how are you doing?  I need your services for SMTP to be able to send
messages to several people please answer me my very dear friend happy new
year 2023

Le lun. 2 janv. 2023 à 08:54, Andreas Nicolai ***@***.***> a
écrit :

**Comment by ghorwin** [comment]
Hmm, seems that GMX does not support STARTTLS anylonger (though still mentioned on webpage), since I cannot get it to work with Tunderbird, either. SslConnection with port 465 works fine with GMX.

**Comment by cheicktra2** [comment]
I don't understand this configuration can I have your telegram if possible?

Le lun. 2 janv. 2023 à 09:28, Andreas Nicolai ***@***.***> a
écrit :
