### ISSUE TITLE
Issues on iOS client with attached file

### ISSUE THREAD

**Issue by bugaenko-cyber** [bluetiger9/SmtpClient-for-Qt#130]
The essence of the problem:
On the iOS client application (Mail), after updating it (it used to work), the download of the attached file stopped working. Writes that the old encryption is used.
But if you open this letter on an android or through any browser, then everything is downloaded. I'll let you know as soon as I get the details. In what direction to dig?

**Comment by bluetiger9** [comment]
@bugaenko-cyber, this looks like a iOS mail client problem. The SMTP client is normally nothing to do with the receiving side / downloading files from the mail server.
