### ISSUE TITLE
Tls 1.3 issue???

### ISSUE THREAD

**Issue by bugaenko-cyber** [bluetiger9/SmtpClient-for-Qt#131]
[SmtpClient] State: ConnectingState
[Socket] State: QAbstractSocket::HostLookupState
[Socket] State: QAbstractSocket::ConnectingState
[Socket] State: QAbstractSocket::ConnectedState
[SmtpClient] State: ConnectedState
[Socket] IN:  "220 **some_server.com** ESMTP Postfix (Ubuntu)\r\n"
[SmtpClient] State: _EHLO_State
[Socket] OUT: "EHLO localhost"
[Socket] IN:  "250-**some_server.com**\r\n"
[Socket] IN:  "250-PIPELINING\r\n"
[Socket] IN:  "250-SIZE 10240000\r\n"
[Socket] IN:  "250-ETRN\r\n"
[Socket] IN:  "250-STARTTLS\r\n"
[Socket] IN:  "250-ENHANCEDSTATUSCODES\r\n"
[Socket] IN:  "250-8BITMIME\r\n"
[Socket] IN:  "250-DSN\r\n"
[Socket] IN:  "250 CHUNKING\r\n"
[SmtpClient] State: _TLS_State
[SmtpClient] State: _TLS_0_STARTTLS
[Socket] OUT: "STARTTLS"
[Socket] IN:  "220 2.0.0 Ready to start TLS\r\n"
[SmtpClient] State: _TLS_1_ENCRYPT
[SmtpClient] State: _TLS_2_EHLO
[Socket] OUT: "EHLO localhost"
[Socket] ERROR: QAbstractSocket::SocketError(20)
[SmtpClient] State: DisconnectingState
[Socket] OUT: "QUIT"
[Socket] State: QAbstractSocket::ClosingState
[Socket] State: QAbstractSocket::ClosingState
[Socket] State: QAbstractSocket::UnconnectedState
[SmtpClient] State: UnconnectedState

Can anyone explain what is the problem??

**Comment by aliks-os** [comment]
I have the same problem. Looks like the openSSL is not visible.

[bugaenko-cyber](https://github.com/bugaenko-cyber)
Did you fixe this issue?

**Comment by bugaenko-cyber** [comment]
I did not find a solution, while everything works on the old server. This problem is new. As soon as I decide I will let you know.

**Comment by aliks-os** [comment]
I already found solution. The libs libcrypto-1_1.dll and libssl-1_1 were added to the binary folder and all works like a charm :)

**Comment by bluetiger9** [comment]
@bugaenko-cyber, please check the solution suggested by @aliks-os. Thanks!
