### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by 627xiaobai** [bluetiger9/SmtpClient-for-Qt#132]
debug model prompt:
QObject::connect: No such signal QSslSocket::errorOccurred(QAbstractSocket::SocketError)
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

relesse model: CMD Show blank, And I didn't receive the email

**Comment by bluetiger9** [comment]
> `QObject::connect: No such signal QSslSocket::errorOccurred(QAbstractSocket::SocketError)`

@627xiaobai, are you using an old version (<= 4.x) of Qt? `QSslSocket::errorOccurred` was added in Qt 5.

> `qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed`

This suggest you have an SSL problem. I would suggest to test SSL connection by creating a simple `QSslSocket` that connects to the SMTP server.
