### ISSUE TITLE
sending multiple mails

### ISSUE THREAD

**Issue by dietmarczekay** [bluetiger9/SmtpClient-for-Qt#133]
What is the best way to send 50 mails to different recipients?
I getting back mails containing failure 554 and every additional mail contains one more recipient in the failure list

**Comment by dietmarczekay** [comment]
[<xxxx.yyyyyy@web.de>](mailto:xxxx.yyyyyy@web.de): host mx-ha02.web.de[212.227.17.8] said: 554-Transaction
    failed 554-Reject due to policy restrictions. 554 For explanation visit
    https://postmaster.web.de/de/case?c=hi&i=ip&v=85.13.140.134 (in reply to
    end of DATA command)

**Comment by bluetiger9** [comment]
@dietmarczekay, sending emails is bulk can be tricky. I would suggest checking with your mail provider what you are allowed to do.
