### ISSUE TITLE
Finding out what when wrong?

### ISSUE THREAD

**Issue by perdrix52** [bluetiger9/SmtpClient-for-Qt#137]
Is there any way for my code to determine what when wrong when any waitForReadyConnected(), waitForAuthenticated(), or waitForMailSent() return false?   

Thanks
David

**Comment by bluetiger9** [comment]
Hi @perdrix52! The `SmtpClient` class defines the `.getResponseCode()` and `.getResponseText()` methods, which return the last _(error)_ response received from the SMTP server.

If that is not enough you could try to enable the `qDebug()` logs to see exactly what happens.

**Comment by perdrix52** [comment]
Thank you
