### ISSUE TITLE
Unable to set Reply-To

### ISSUE THREAD

**Issue by ChriswZeroOne** [bluetiger9/SmtpClient-for-Qt#141]
I am unable to figure out how to set the Reply-To. Is this even possible?

**Comment by attila-tokes** [comment]
I think you should be able to add a `Reply-To` address by setting a custom header on the `MimeMessage`:
```
MimeMessage message;
...
message.addCustomHeader("Reply-To: <your-reply-addr@example.com>");
```

**Comment by ChriswZeroOne** [comment]
Thanks, that worked perfectly for what I was trying to accomplish. Here's another question, what would be the best way to hook in a progress bar after the call to sendMail it shows in your examples to call waitForMailSent which does not return until completion or error.
    On Tuesday, July 18, 2023 at 09:03:02 AM PDT, Attila Tőkés ***@***.***> wrote:  
 
 


I think you should be able to add a Reply-To address by setting a custom header on the MimeMessage:
MimeMessage message;
...
message.addCustomHeader("Reply-To: ***@***.***>");
