### ISSUE TITLE
compile of 2.0 fails

### ISSUE THREAD

**Issue by dietmarczekay** [bluetiger9/SmtpClient-for-Qt#143]
qmake says it can't find "_QUITTING_State".
Where is this state defined?

**Comment by ghost** [comment]
Hi,
I had the same problem and added I added __QUITTING_State = 56,_ below __READY_Encrypted = 55,_  to smtpclient.h 
and I added _bool waitForDisconnected(int msec);_ his was also not declared in the header. After this changes I can compile the library for Qt5 and Qt6 on Linux. Windows I didn't check yet.

Regards

**Comment by dietmarczekay** [comment]
I checked both, linux and win64. Both works.

**Comment by bluetiger9** [comment]
Fixed this with https://github.com/bluetiger9/SmtpClient-for-Qt/commit/24265e19b12f57c9bc1ccbed24fc4f9fbadae237. Thanks!

**Comment by dietmarczekay** [comment]
Thanks for fixing
