### ISSUE TITLE
Exception triggered by MimeMessage addPart

### ISSUE THREAD

**Issue by BL-Bl4ckBut7ch3r** [bluetiger9/SmtpClient-for-Qt#153]
Hi there!

I managed to setup this client on Windows (irrevelant but, I use Win 11 pro) but as I send the e-mail out (which does arrive to the client) it crashes my program with no clear indication of what the SmtpClient screws up. Currently I'm **using Qt Creator 5.0.2 with MinGW 64bit**.

What I was able to track down so far are the following:

The line in my code that fails: `message.addPart(&text);`

Here is an example of what kind of data do I pass to the text variable: `text.setText(ui->OutputLabel->toPlainText());` (OutputLabel is a QTextBrowser and from that straight the QString)

The QString looks like this all of the times: (example and also for consistency test I never changed the QString which I would send) **hthIhtfadEc8stdEyvkKz9hsyxhIyvkKdEbtyoa5yvkKc8hIhthIhtfahthIyzbtdEbtyoa5yvkKc8hIyvkKz9hsc8hIc8ZryxdDraezhthIyzbtyxdDraezhthIyzbtJkhIa5gac8hIhxGcJkbtz9hsJkbtz9hsgac8gac89b9b==**

And in debug mode I get this:

![image](https://github.com/bluetiger9/SmtpClient-for-Qt/assets/64802101/26f58916-be9b-412e-8ad3-e241594bc702)

![image](https://github.com/bluetiger9/SmtpClient-for-Qt/assets/64802101/fc58fecb-80ab-45e7-b384-18a542bb7c59)

![image](https://github.com/bluetiger9/SmtpClient-for-Qt/assets/64802101/4c6bdad0-253f-4243-a874-5849d14faee6)

After this I tracked to the issue causer as much as I could (see after this phrase), but from here on I don't really know what should I do.

The function that kills it: 
```
void MimeMessage::addPart(MimePart *part)
{
    if (typeid(*content) == typeid(MimeMultiPart)) {
        ((MimeMultiPart*) content)->addPart(part);
    };
}
```

Thank you for your help in advance!

**Comment by attila-tokes** [comment]
The `MimeMultiPart.addPart(...)` method takes ownership on the parts you pass as parameters. In the destructor the parts are also deleted, and I think you program may fail because of a double deletion of the `MimeText` object.

One thing you could try, is to create the `MimeText` object on the heap with `new MimeText(...)`, instead of creating it on the stack.

**Comment by BL-Bl4ckBut7ch3r** [comment]
I will test it right away.

**Comment by BL-Bl4ckBut7ch3r** [comment]
That solves the issue. Thanks.

(Minor other thing is i get `QObject::connect: No such signal QSslSocket::errorOccurred(QAbstractSocket::SocketError)`
I did modify the cpp to connect to error instead of errorOccurred but it didn't seemed to affect this one problem, although I will ignore it for now)

**Comment by bluetiger9** [comment]
> (Minor other thing is i get `QObject::connect: No such signal QSslSocket::errorOccurred(QAbstractSocket::SocketError)`
> I did modify the cpp to connect to error instead of errorOccurred but it didn't seemed to affect this one problem, although I will ignore it for now)

In recent versions of Qt 5/6 (>5.15) the `QAbstractSocket::error` signal was renamed to `errorOccurred`.
