### ISSUE TITLE
For 6.7.0 it does not compile without this

### ISSUE THREAD

**Issue by bugaenko-cyber** [bluetiger9/SmtpClient-for-Qt#155]
find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Network)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core Network)

**Comment by attila-tokes** [comment]
Compile with CMake seems to be fine both with Qt 6.7.x and Qt 6.5.x. The `Core` and `Network` packages are already included in [CmakeList.txt](https://github.com/bluetiger9/SmtpClient-for-Qt/blame/v2.0/src/CMakeLists.txt#L12).

How I tried to compile with CMake:
```
$ mkdir build-qt-6.x.x && cd build-qt-6.x.x
$ cmake -DQT_VERSION_MAJOR=6 -DCMAKE_PREFIX_PATH=/path/to/qt/6.x.x/gcc_64/lib/cmake/Qt6/ ../src
$ cmake --build .

```
