### ISSUE TITLE
It actually send email but crashes the application

### ISSUE THREAD

**Issue by jancotipsarevic** [bluetiger9/SmtpClient-for-Qt#160]
Hello, the library crashes the application executing sendMail function but the email is successfully sent.
Qt version:6.7.2
Kits tested:MinGW_64_bit and MSVC2019_64bit
Connection Type: TcpConnection
Thank you very much

**Comment by ocgltd** [comment]
I suspect this is duplicate of [this issue](https://github.com/bluetiger9/SmtpClient-for-Qt/issues/158)

Cause is freeing pointer it should not

**Comment by jancotipsarevic** [comment]
Yes it looks may be the same, thank you.

**Comment by bluetiger9** [comment]
This should be fixed now. See #158.
