### ISSUE TITLE
CmakeLists.txt and .pro file generates libs with different names

### ISSUE THREAD

**Issue by EgorWeders** [bluetiger9/SmtpClient-for-Qt#164]
In CMakeLists.txt
`project(Qt${QT_VERSION_MAJOR}SmtpMime VERSION 0.1 LANGUAGES CXX)
`
In SMTPEmail.pro
`
TARGET = SmtpMime
`

**Comment by mozhongzhou** [comment]
自动回复：已收到您的邮件
