### ISSUE TITLE
SmtpClient needs to adjust to server supported features, e.g. force using AUTH PLAIN if it the only method supported.

### ISSUE THREAD

**Issue by ahmedbd84** [bluetiger9/SmtpClient-for-Qt#165]
in smtpclient.cpp, the response of sending **EHLO** returns supported features by the mail server.
one example is the authorization supported methods.
normally we would receive:
**250-AUTH PLAIN LOGIN**
that means both PLAIN, and LOGIN are supported methods.

but sometimes the server returns:
**250-AUTH PLAIN**
or 
**250-AUTH=PLAIN**
that means only PLAIN method supported, so the SmtpClient class needs to FORCE using **AUTH PLAIN**, even if user specified **AUTH LOGIN** method or at least log the conflict as the mail server wouldn't accept the autherization, and you might get the following error response: 
5.7.8 Error: authentication failed: Invalid authentication mechanism

or a similar response.

**Comment by bluetiger9** [comment]
Hello @ahmedbd84! :slightly_smiling_face:

The library does not currently tries to parse the `EHLO` response. It just uses the authentication method the user specified in the `.login()` method.

In case you dynamically decide between `AUTH LOGIN` and `AUTH PLAIN`, you may be able to parse the `EHLO` response manually. There is a `SmtpClient::getResponseText()` method that returns the last response from the server. You should be able to call this after `.waitForReadyConnected()` completes (may not work with `TlsConnection`).

Thanks,
Attila
