### ISSUE TITLE
Chinese title and sender may have garbled characters

### ISSUE THREAD

**Issue by Vdeilae** [bluetiger9/SmtpClient-for-Qt#168]
just like this ”��“

**Comment by mozhongzhou** [comment]
自动回复：已收到您的邮件

**Comment by bluetiger9** [comment]
@Vdeilae, try setting the header encoding to `QuotedPrintable` or `Base64`. Some servers and clients may have trouble with plain UTF-8. See [`MimeMessage::setHeaderEncoding()`](https://github.com/bluetiger9/SmtpClient-for-Qt/blob/v2.0/src/mimemessage.h#L61) reference.
