### ISSUE TITLE
Shipping SmtpMime.so

### ISSUE THREAD

**Issue by perdrix52** [bluetiger9/SmtpClient-for-Qt#171]
You appear only build as a shared library and -DBUILD_SHARED_LIBS=OFF is ignored.

This means that I can't include the code into my executable, so users of my code need to have libSmptMine.so.2.0 and related symlinks available.

I hope that this means that you are happy for me to distribute the library with my code?

Thanks
David

**Comment by mozhongzhou** [comment]
自动回复：已收到您的邮件

**Comment by attila-tokes** [comment]
@perdrix52, the library is designed to be built exclusively as a shared library. 🙂  As it is licensed under LGPL, it is fine to distribute the compiled version of the shared library along with your software. Thanks!

**Comment by perdrix52** [comment]
Hi again, I think it would be nice if you did allow building as a static library - it does work well built that way
