### ISSUE TITLE
One question, I add the cpp and .h files in my project, but its not work.

### ISSUE THREAD

**Issue by Kaio1394** [bluetiger9/SmtpClient-for-Qt#173]
Error:
![image](https://github.com/user-attachments/assets/8e8317c4-80d5-49ae-9cec-2e003cf25304)

My file .pro:

`QT       += core gui network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

SOURCES += \
    emailaddress.cpp \
    main.cpp \
    mimeattachment.cpp \
    mimebase64encoder.cpp \
    mimebase64formatter.cpp \
    mimebytearrayattachment.cpp \
    mimecontentencoder.cpp \
    mimecontentformatter.cpp \
    mimefile.cpp \
    mimehtml.cpp \
    mimeinlinefile.cpp \
    mimemessage.cpp \
    mimemultipart.cpp \
    mimepart.cpp \
    mimeqpencoder.cpp \
    mimeqpformatter.cpp \
    mimetext.cpp \
    quotedprintable.cpp \
    sendemailspage.cpp \
    smtpclient.cpp

HEADERS += \
    SmtpMime.h \
    emailaddress.h \
    mimeattachment.h \
    mimebase64encoder.h \
    mimebase64formatter.h \
    mimebytearrayattachment.h \
    mimecontentencoder.h \
    mimecontentformatter.h \
    mimefile.h \
    mimehtml.h \
    mimeinlinefile.h \
    mimemessage.h \
    mimemultipart.h \
    mimepart.h \
    mimeqpencoder.h \
    mimeqpformatter.h \
    mimetext.h \
    quotedprintable.h \
    sendemailspage.h \
    smtpclient.h \
    smtpmime_global.h

FORMS += \
    sendemailspage.ui

qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    resource.qrc

SUBDIRS += \
    SMTPEmail.pro
`

**Comment by attila-tokes** [comment]
Hi @Kaio1394! 🙂

The library is supposed to be build a as shared library:
1. First build the library project ([SMTPEmail.pro](https://github.com/bluetiger9/SmtpClient-for-Qt/blob/v2.0/src/SMTPEmail.pro)). This will produce a shared library in the form of a `.dll` or `.so` file.
2. Then link the library in your project. The 2nd demo project ([demo2.pro](https://github.com/bluetiger9/SmtpClient-for-Qt/blob/v2.0/demos/demo2/demo2.pro)) shows an example with UI components.

Thanks!
