### ISSUE TITLE
building for windows

### ISSUE THREAD

**Issue by Stamper** [bluetiger9/SmtpClient-for-Qt#33]
hello!
please, help me with building for windows. on linux everything is going perfectly.
but on windows:
C:\QtProjects\atmail\emailaddress.cpp:23: warning: 'EmailAddress::EmailAddress(const QString&, const QString&)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 EmailAddress::EmailAddress(const QString & address, const QString & name)
 ^
C:\QtProjects\atmail\emailaddress.cpp:23: error: undefined reference to `_imp___ZTV12EmailAddress'

and many other similar messages. what am i doing wrong? thank you

**Comment by Stamper** [comment]
Windows XP x86, Qt 5.3, MinGW 32bit

**Comment by Stamper** [comment]
I'm not sure what has happened, but my app built when I changed line 7 at smtpexports.h to:
#define SMTP_EXPORT Q_DECL_EXPORT

**Comment by bluetiger9** [comment]
Hi. Probably you leaved the ```win32:CONFIG += dll``` flag on, while compiling with ```TEMPLATE = app```.

To the project as an application, just comment out the library section from the ```.pro``` file:
```
# Build as an application
TEMPLATE = app

# Build as a library
#TEMPLATE = lib
#DEFINES += SMTP_BUILD
#win32:CONFIG += dll
```
