### ISSUE TITLE
Possible memory leak.

### ISSUE THREAD

**Issue by dearn44** [bluetiger9/SmtpClient-for-Qt#36]
Each time you send a new email the memory consumption increases by a little bit. This could become a problem if you keep the client open for a long time.

Not sure where the leak is yet though.

Tested in:
-MacOS Mavericks
-Qt 5.3
-Using Demo1

**Comment by claud84** [comment]
I think there is some issue is with the MimeMessage class destructor;
Not everything gets cleaned up, for instance the sender pointer and the recipients list don't get cleaned. 
Any other ideas?

**Comment by dearn44** [comment]
I did some more tests and I think it should not present an issue, as whatever leak is very small. Maybe if you take care of the pointers to the various email data after the email is sent will eliminate the problem.

**Comment by trevtb** [comment]
Hello, I am facing the same problem and my application is a daemon intended to run for a very long time (it is an alarm system). I already updated my sources to use the newest version as I used version 1.0 before which was outdated. This actually fixed some of the issues as the .jpgs I attach are now correctly cleared from memory after the email is sent. 

Still my memory consumption grows by about 1 megabyte (!!) each time I send a mail. I always create a new instance of smtpclient and correctly delete it when finished so it is not my code causing the issue. If I replace the call to smtpclient with a qDebug message in my code then I don't get any memory leaks at all. The way it is now my device will run out of memory after a few months of service.

Please help!

**Comment by dearn44** [comment]
To be honest after failing to find the issue after trying a couple of times I stopped trying and accepted it as it is. Maybe @claud84 has made any progress.

**Comment by trevtb** [comment]
Thank you for your honesty. I really love the smtpclient and would like to keep it, even though I found alternatives now. I am not a QT crack and after reviewing the source code there is only one thing I noticed regarding the issue:

The parent pointer (QObject *parent) is not being used in any constructor even though all objects inherit from QObject as you can see in the header files. QT uses this pointer for cleanup processes when the parent gets deleted so it is necessary for garbage collection.
Again: I am no QT crack and don't want to imply that this is wrong or bad coding. This is just an idea based on my limited knowledge and there might be good reasons for the smtpclient not to use the parent pointer. Maybe someone can comment on that? Maybe that's a reason for the spotted behaviour?

Thanks in advance!

**Comment by bluetiger9** [comment]
I found a possible cause: the `socket` used in the `SmtpClient` class was not deleted properly.
I pushed the fix, can you try it now?
