### ISSUE TITLE
Getting linker error

### ISSUE THREAD

**Issue by AttitudeMonger** [bluetiger9/SmtpClient-for-Qt#37]
I guess there are some libraries which I need to include, but they are not mentioned anywhere. Anyway, I just included the source folder in my includepath and tried to build it. With the basic example given in the doc, this is the error I am getting (platform - OS X Yosemite 10.10.2, Qt 5.3.1 32 bit)

Undefined symbols for architecture i386:
  "SmtpClient::setPassword(QString const&)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "SmtpClient::connectToHost()", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "SmtpClient::quit()", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "SmtpClient::login()", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "SmtpClient::setUser(QString const&)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "SmtpClient::sendMail(MimeMessage&)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "SmtpClient::SmtpClient(QString const&, int, SmtpClient::ConnectionType)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "SmtpClient::~SmtpClient()", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeMessage::setSubject(QString const&)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeMessage::addRecipient(EmailAddress_, MimeMessage::RecipientType)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeMessage::addPart(MimePart_)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeMessage::setSender(EmailAddress_)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeMessage::MimeMessage(bool)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeMessage::~MimeMessage()", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "EmailAddress::EmailAddress(QString const&, QString const&)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "EmailAddress::~EmailAddress()", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeText::setText(QString const&)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeText::MimeText(QString const&)", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
  "MimeText::~MimeText()", referenced from:
      MailSender::MailSender() in some_app_library.a(MailSender.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *_\* [MyApp.app/Contents/MacOS/MyApp] Error 1
22:36:24: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project MyApp (kit: MyApp)
When executing step 'Make'

Any idea how to fix this?

**Comment by bluetiger9** [comment]
Closing. Seems to work with the latest version.

**Comment by FinrodFelegund** [comment]
Hello there, 
I am getting this linker errors, too : 
/Users/danielpietsch/build-SMTP-Desktop_x86_darwin_generic_mach_o_64bit-Debug/main.o:-1: Fehler: Undefined symbols for architecture x86_64:
  "SimpleMail::MimeMessage::setSubject(QString const&)", referenced from:
      _main in main.o
  "SimpleMail::MimeMessage::addTo(SimpleMail::EmailAddress const&)", referenced from:
      _main in main.o
  "SimpleMail::MimeMessage::addPart(SimpleMail::MimePart*)", referenced from:
      _main in main.o
  "SimpleMail::MimeMessage::setSender(SimpleMail::EmailAddress const&)", referenced from:
      _main in main.o
  "SimpleMail::MimeMessage::MimeMessage(bool)", referenced from:
      _main in main.o
  "SimpleMail::MimeMessage::~MimeMessage()", referenced from:
      _main in main.o
  "SimpleMail::EmailAddress::EmailAddress(QString const&, QString const&)", referenced from:
      _main in main.o
  "SimpleMail::EmailAddress::~EmailAddress()", referenced from:
      _main in main.o
  "SimpleMail::Sender::setPassword(QString const&)", referenced from:
      _main in main.o
  "SimpleMail::Sender::quit()", referenced from:
      _main in main.o
  "SimpleMail::Sender::setUser(QString const&)", referenced from:
      _main in main.o
  "SimpleMail::Sender::sendMail(SimpleMail::MimeMessage const&)", referenced from:
      _main in main.o
  "SimpleMail::Sender::Sender(QString const&, int, SimpleMail::Sender::ConnectionType, QObject*)", referenced from:
      _main in main.o
  "SimpleMail::Sender::~Sender()", referenced from:
      _main in main.o
  "SimpleMail::MimeText::setText(QString const&)", referenced from:
      _main in main.o
  "SimpleMail::MimeText::MimeText(QString const&)", referenced from:
      _main in main.o
  "SimpleMail::MimeText::~MimeText()", referenced from:
      _main in main.o
  "SimpleMail::Sender::lastError() const", referenced from:
      _main in main.o

Any Ideas how to fix it?
best regards

**Comment by bluetiger9** [comment]
Hmm, I suppose the shared library is not included in MacOS for some reason.

There should be an if-else structure for win32 / unix in the `.pro` file:
```
win32:CONFIG(release, debug|release): LIBS += -L$$SMTP_LIBRARY_LOCATION/release/ -lSMTPEmail
else:win32:CONFIG(debug, debug|release): LIBS += -L$$SMTP_LIBRARY_LOCATION/debug/ -lSMTPEmail
else:unix: LIBS += -L$$SMTP_LIBRARY_LOCATION -lSMTPEmail
```
I'm not sure how this behaves on MacOS.

Could you try to replace that with:
```
LIBS += -L$$SMTP_LIBRARY_LOCATION -lSMTPEmail
```
and try if it works?

**Comment by FinrodFelegund** [comment]
I commented out this:
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

and replaced it with what you sent, but nothing changed

**Comment by bluetiger9** [comment]
Is the shared library correctly built when you build `SMTPEmail.pro`? There should be a the `SMTPEmail.so` or `SMTPEmail.dylib` file, I think.

That shared library file then needs to be used at link time at your project.

This is done by adding the following the `.pro` file:
```
# Location of SMTP Library
SMTP_LIBRARY_LOCATION = $$PWD/../../../build/SMTPEmail-Desktop-Debug

LIBS += -L$$SMTP_LIBRARY_LOCATION -lSMTPEmail
```

The `SMTP_LIBRARY_LOCATION` points to the location where the shared library is.

**Comment by FinrodFelegund** [comment]
The error from above does not appear anymore, but now it says: :-1: Fehler: library not found for -lSMTPEmail

**Comment by bluetiger9** [comment]
This probably means the `SMTP_LIBRARY_LOCATION` points to the wrong folder. 

It needs to point where the `SMTPEmail.so` or `SMTPEmail.dylib` is located.

**Comment by FinrodFelegund** [comment]
Well I think I missunderstood your first hint. Now I tried to build the SMTPEmail.pro file and there are several errors regarding an append function. It appears the parameter it expects is a QString but it gets a char or it is the other way around not sure

**Comment by FinrodFelegund** [comment]
Just to let you know, I managed to get the library running. Thanks for the help!
