### ISSUE TITLE
Q_DECLARE_METATYPE(SmtpClient::SmtpError)

### ISSUE THREAD

**Issue by okadaygen** [bluetiger9/SmtpClient-for-Qt#38]
First, thank you for the great helpful library.

It seems smtpError signal defined in SmtpClient.h doesn't allow slots outside of  the library(SmtpClient-for-Qt) to receive it.

If Q_DECLARE_METATYPE(SmtpClient::SmtpError) is declared in SmtpClient.h, my application can receive the signal and know what kinds of error occurred in SmtpClient.

Or, is there a better way to obtain error details from outside of the library?

Thanks,

**Comment by bluetiger9** [comment]
Hello, and sorry for the late answer!

Unfortunately I was not able to reproduce the problem. I can connect the ```smtpError``` to slots from external code, even if I use dynamic linking.

Example code, to connect ```smtpError``` to your slot:
```
    QObject::connect(&smtp, &SmtpClient::smtpError,
                         this, &YourClass::smtpError);
```

Can you please give me more details about the issue (example code, error messages, etc.)?

Thanks,

Attila

**PS:**
Beside the ```smtpError``` signal, you can use the ```bool``` values returned by the ```connectToHost()```, ```login()``` and ```sendMail()``` methods to see if the operation was successful or not. If the operation failed, you can use the ```getResponseText()``` and ```getResponseCode()``` method to get the exact error message returned by the server.
