### ISSUE TITLE
:-1: error: cannot find -lSMTPEmail

### ISSUE THREAD

**Issue by adevans2** [bluetiger9/SmtpClient-for-Qt#40]
Thank you for the the libraries!

I have only been using QT for approximately 5 weeks, so you can say that I am a beginner, and possibly this is a novice question.

I have this error when I run one of the demo files: 
@ -1: error: cannot find -lSMTPEmail @

I think the error is caused in the .pro file after # Location of SMTP Library # is defined. Am I right in assuming the path is wrong or the file doesn't exist?

The only file I have found that contains 'SMTPEmail' is the Project located alongside the Readme.

By the way, I have read the readme for any initial setup instructions.

Thank you in advance!

**Comment by bluetiger9** [comment]
Hi,

First you have to build the library project (```SMTPEmail.pro```). This will produce a dynamic library called ```SMTPEmail``` (extension depends on OS). This will be placed in the configured build directory. You need to set the ```SMTP_LIBRARY_LOCATION``` to this directory in the demo project (```demo*.pro```).

Regards,
Attila

**Comment by adevans2** [comment]
It works, thank you for your help!

**Comment by bluetiger9** [comment]
You're welcome.
