### ISSUE TITLE
Show message Mail failed

### ISSUE THREAD

**Issue by NJ08** [bluetiger9/SmtpClient-for-Qt#46]
Mail Send successfully with attachments But because of exceptions shows mail failed.

**Comment by bluetiger9** [comment]
Probably the sending takes longer because of the attachament. Try setting a higher send timeout:
```
void setSendMessageTimeout(int msec);
```

Thanks!

**Comment by NJ08** [comment]
Hello,

Thanks it works but i have to set response time too
please find out the attachment i send you my codes screenshot.
I want to know that what i did is correct or not??
and is it affect any other functionality??
if yes then what value can i set for msgSending time and response time.

Please reply.


Thanks,

**Comment by bluetiger9** [comment]
Hi,

With ```setSendMessageTimeout``` you can set how much do you want wait to send a message. The sending time of a message, mainly depends on your connection with the mail server and the size of your attachments.

The ```setResponseTimeout``` you can say how much do you want to wait for the server's response. The response time depends on mail server and on the connection to it.

You may set this values based on your requirements. If you are sending big attachments or the connection with the mail server is slower just set higher timeouts.

Thanks,
Attila

**Comment by NJ08** [comment]
So whatever right now as you see my attached code is right for me there in
no harm in that???

**Comment by bluetiger9** [comment]
I don't see any attached code. Can you please send me to the tokes_atti@yahoo.com address?
