### ISSUE TITLE
Trouble using Win8

### ISSUE THREAD

**Issue by flothi** [bluetiger9/SmtpClient-for-Qt#47]
hi, I tried to use the dll (built with MinGW in Win7, x64) with Win8 - although I use the same parameters, I am unable to send mails through Win8; the only error I get is "Unable to connect to host". 
Is there any dependency missing?

**Comment by bluetiger9** [comment]
Maybe it's a network problem. Can you try to connect with Telnet to the mail server?

**Comment by flothi** [comment]
I am able to connect via PuTTY; while debugging I found out that I need the libeay32.dll and ssleay32.dll, which were not set up on my VM - I expect another DLL missing...

**Comment by bluetiger9** [comment]
These are the OpenSSL dll-s needed for SSL connections. It's still not working if you put these in your folder with the executable?

You could try to use [Dependency Walker](http://www.dependencywalker.com/) to find out what DLLs are missing...

**Comment by flothi** [comment]
I copied the files into the directory, but it has no positive effect. 
Both Dependency Walker and Debug with Creator show no further required DLL 
I will keep testing.

**Comment by bluetiger9** [comment]
Closing. TLS/SSL works with Windows 10.

**Comment by vinaykulkarni89** [comment]
Facing same issue
