### ISSUE TITLE
MimeMessage: memory leaks

### ISSUE THREAD

**Issue by mrcheko** [bluetiger9/SmtpClient-for-Qt#50]
Hi. I bet you have memory leaks in the `MimeMessage` class: 
`QList<EmailAddress*> recipientsTo, recipientsCc, recipientsBcc;` - element pointers are not deleted anywhere while corresponding set-methods like `addRecipient` supposedly should set ownership to `MimeMessage`'s object (?). At least Qt itself does things in that way. Otherwise you should rewrite your examples cause there are memory leaks definitely.

**Comment by teemartins** [comment]
Memory leaks will also come from MimePart* content if setContent is called.
