### ISSUE TITLE
Multiple Undefined Reference Errors on 2.0 DEV Qt5

### ISSUE THREAD

**Issue by cxammar** [bluetiger9/SmtpClient-for-Qt#57]
Hi I just copied an example of the 2.0dev to my code but it's giving me a lot of undefined reference errors, which are: 
![errors](https://cloud.githubusercontent.com/assets/11465431/25498200/642f0bb6-2b87-11e7-99c1-33affdc7a772.PNG)

**Comment by Arobce** [comment]
Same Problem. Did you find out how to fix it?

**Comment by bluetiger9** [comment]
Apparently You are trying to build the examples from the `dev` branch (`v2.0`) against `v1.1` shared library. 
The API was somewhat changed in `v2.0`, so the examples will need the `v2.0` lib.

You can build the examples as follows:
- clone / download the `dev` (v2.0) branch
- open and build the `src/SMTPEmail.pro`
- open and build one of the demo projects (`demos/demoX/demoX.pro`)
  - you may need to change `SMTP_LIBRARY_LOCATION`
  - you may also need to replace `-lSMTPEmail` to `-lSMTPMime` in `LIBS`
