### ISSUE TITLE
Freeze on some systems

### ISSUE THREAD

**Issue by Swerved** [bluetiger9/SmtpClient-for-Qt#60]
I've had reports from some users that it freezes on sending the email, the application locks up and the email never sends. 

Unfortunately not got a clue what is causing the issue, some have anti virus set up, and others do not.

Same code works completely fine for me.

For now I've to pull this out of some of my code, and leave it in the one part where it doesn't really matter so much (Breakpad call back).

**Comment by bluetiger9** [comment]
Hi!

I would have a couple of questions:
- which version of the library are you using, 1.1 or 2.0?
- at which the step (connect, auth, mail sending) the application freezes?
- there is default timeout (1 min) after which the an error is returned, normally. Does this happens?

Thanks,
Attila

**Comment by Swerved** [comment]
- v1.1
- Mail Sending I'm reasonably certain -- but I will insert some debug output to finding 
- Nope, nothing is returned.

I do have a sendMail as the condition for an if bracket; so, if it succeeds, I can make sure I do some cleanup: 

---

// Now we can send the mail

        smtp.connectToHost();
        smtp.login();
        if (smtp.sendMail(message)) // Delete file when it is sent if successful, otherwise it stays in the crash folder.
        {
             crashFile.remove(crashdumpfilename);
             QFile::remove(screenshot);
        }
        smtp.quit();

-- 
As mentioned here (only place I have this code now), if it causes an issue at this point for the users affected, it is not going to make a difference anyway as the application has already crashed.

**Comment by bluetiger9** [comment]
Are you calling this code from the application that just crashed? If you are not doing already, it may worth a try to do the mail sending from newly started process.

**Comment by Swerved** [comment]
> Are you calling this code from the application that just crashed? If you are not doing already, it may worth a try to do the mail sending from a newly started process.

Tried both actually (see previous post edit section) -- it's just because I was having the issue I removed it from my code where it causing an issue in general use, but left it in for the Breakpad callback as it does work for some (but not all), users.

So for me: 

Sending email when application crashed = works
Sending email when application is running = works

But it doesn't work in either case for some of my users.

Hope that clarifies the situation.I am a little stumped what it might be, unfortunately.

**Comment by bluetiger9** [comment]
It's clear now, but I think we would need some more info to figure out what causes the freeze. Is there any chance to get some stack traces or a core dump, from the users experiencing the freeze under normal use?

**Comment by Swerved** [comment]
I will try getting a core dump from a user, and see what I can give you. With it being huge, I hope one of them is willing to upload it for me to take a look! Will get back to you when I hear back from an affected user.

**Comment by Swerved** [comment]
I got a core dump, the most I can figure is that it is crashing in QtNetwork.dll. Unfortunately don't have the symbols from the version the user was using, he was 3 versions behind. 

I'd consider the matter closed now - as I would have to revert my changes to reproduce the issue in 'normal use', and these changes were planned for now anyway.
