### ISSUE TITLE
v1.1 can not be build for Qt4

### ISSUE THREAD

**Issue by thesourcehim** [bluetiger9/SmtpClient-for-Qt#62]
src/mimemessage.cpp: In member function ‘virtual QString MimeMessage::toString()’:
src/mimemessage.cpp:265:83: error: ‘RFC2822Date’ is not a member of ‘Qt’
     mime += QString("Date: %1\r\n").arg(QDateTime::currentDateTime().toString(Qt::RFC2822Date));

RFC2822Date is not present in Qt 4.8.7, only Qt5.

**Comment by esilvia** [comment]
@thesourcehim I managed to fix this for myself with pull request 69. Let me know if it doesn't work for you.
