### ISSUE TITLE
Problem with deployment

### ISSUE THREAD

**Issue by andrortizster** [bluetiger9/SmtpClient-for-Qt#64]
I wrote an app that use SmtpClient dll, when I deploy the app in a folder with all QT's dll in my PC works fine, the app connect with email server and send messages with no problems, but when I copy the folder to another PC the app is not working, do not connect with server and do not send messages.

**Comment by bluetiger9** [comment]
Most likely the connection to the mail server is blocked by a firewall or by your ISP. You could check this by telneting the mail server on the used port.
