### ISSUE TITLE
TLS without Certificate

### ISSUE THREAD

**Issue by CodeMantle** [bluetiger9/SmtpClient-for-Qt#65]
Using TLS, the 'connectToHost' consistently fails to a SMTP server that is proven to be working fine on other connections. With the SmtpClient-for-Qt, it reports a 'certificate not found' error.
Looking at smtpclient.cpp, it fails on the 'startClientEncryption' call, with the message 'The issuer certificate of a locally looked up certificate could not be found'.
I have read that certificates are (very?) rare in SMTP servers, and if so, I wonder why it fails for this reason?
I have an SSL-based SMTP server that works fine, so the 'SslConnection' is ok, just the 'TlsConnection' won't get past this point.
Thanks for any assistance.

**Comment by bluetiger9** [comment]
This sound like the server's SSL certificate cannot be validated. Can you check the SSL certificate of the server? You should have the certificate's Root Certification Authority (CA) installed on your machine.

**Comment by CodeMantle** [comment]
Sorry for not getting back before. I did not get a chance to prove this, but I guess that is exactly what is wrong here.
It is OK to close the issue.
