### ISSUE TITLE
dev branch: QTimer in QEventLoop

### ISSUE THREAD

**Issue by Letrab** [bluetiger9/SmtpClient-for-Qt#66]
Apparently, running an application with multiple threads can cause issues with QTimers not running in the same thread/eventloop.
The QThread doesn't fire its timeout() signal to the QEventLoop if it is running in another thread.

To fix this, in SmtpClient::waitForEvent ,the timer could be created dynamically and parented to the QEventLoop:

```
    QEventLoop loop;
    QTimer *timer = new QTimer(&loop);
    ...
    loop.exec()
    delete timer;
```

For me, in this case, I can get the timer to timeout. I hope there is no extra risk/memory leak involving this.

**Comment by opengpu** [comment]
do i have to change some code in the lib, if i sendMail in another thread?

**Comment by bluetiger9** [comment]
I think doing all the interaction with a `SmtpClient` from the same thread should work. This includes creating the object, and calling the `connectToHost()`, `login()`, `sendMail()`, `quit()` and `waitFor...()` method from the same thread.

So, to delegate email sending to a different thread, I would recommend moving all interactions to a new thread. Calling just the `sendMail()` may not work reliably.
