### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by nonBorg** [bluetiger9/SmtpClient-for-Qt#67]
Issue sometimes coming up failed even though succeeded to send.

Small change required to fix in the SmtpClient::waitForResponse routine.
void SmtpClient::waitForResponse()
{
    do {
        if (!socket->waitForReadyRead(responseTimeout))
        {
            emit smtpError(ResponseTimeoutError);
            throw ResponseTimeoutException();
        }
        if(socket->isOpen()){ // <<-- added this if to solve issue, suspect the issue was related to the server I am using.
            while (socket->canReadLine()) {
                // Save the server's response
                responseText = socket->readLine();

                // Extract the respose code from the server's responce (first 3 digits)
                responseCode = responseText.left(3).toInt();

                if (responseCode / 100 == 4)

                    emit smtpError(ServerError);

                if (responseCode / 100 == 5)
                    emit smtpError(ClientError);

                if (responseText[3] == ' ') { return; }
            }
        }
    } while (true);
}

**Comment by Perrahmaouy** [comment]
Hi nonBorg,
The issue you mentioned truly exists. While working with simple mails, or mails with lightweight attachements the issue wouldn't occur, but when I was sending mails with pdf files (> 65ko), I started getting this error. Your line fixed the issue, Thanks.
