### ISSUE TITLE
Memory leak in Example 2

### ISSUE THREAD

**Issue by esilvia** [bluetiger9/SmtpClient-for-Qt#68]
I believe there's a memory leak in Example 2 as written. As far as I can tell, the second `MimeAttachment` added to the message isn't ever deallocated because `message` doesn't take ownership of the parts added with `MimeMessage::addPart()`.

Is that correct?

**Comment by Wzzzx** [comment]
Yeap, this is the bug of this project. The author forget to delete the `MimeAttachment`

**Comment by Wzzzx** [comment]
I use this way to auto-delete `MimeAttachment`. 
```
MimeMessage message;
MimeAttachment *attachment = new MimeAttachment(new QFile("file"));
attachment->setParent(&message);
```

**Comment by JanKovis** [comment]
Or having recipients as dynamically allocated EmailAddress instances is not quite correct. I have overhauled this, but apparently author does not care to pull pull requests...

**Comment by bluetiger9** [comment]
Updated the examples for v1.1. The v2.0 version of the library no longer uses pointer for the set email sender / recipient methods.
