### ISSUE TITLE
Is SmtpClient threadsafe?

### ISSUE THREAD

**Issue by meteoir** [bluetiger9/SmtpClient-for-Qt#70]
Hello!
DLL works perfectly!
But I'm interesting - is using a demo1 example thread safe?
I want to use dll without QApplication. It's possible? 
I already check this and it works, but what about thread safety with multiple mail sends?

**Comment by opengpu** [comment]
is it thread-safe?

**Comment by bluetiger9** [comment]
The `SmtpClient` class is not thread safe, but you can instantiate a new `SmptClient` object each time you send a mail.

For non UI application, `QCoreApplication` could be used instead of the `QApplication`.

**Comment by opengpu** [comment]
is it fast to instantiate a new SmptClient object each time you send a mail.?

**Comment by opengpu** [comment]
can i set a timeout ?
because it seems that i have to "instantiate a new SmptClient object each time you send a mail." in mainThread... and there is data updating at realtime very frequently at mainThread

**Comment by bluetiger9** [comment]
@opengpu, creating the new `SmtpClient` should be fast, as the constructor just sets some fields. The slow part usually will be the call to `connectToHost()`, `.login()` and `.sendMail()` methods, as these involve network communication.

The mail sending could block the current thread up to the connect / response / send timeouts _(5, 5 and 60 seconds by default).

I would recommend to have a dedicated thread for sending the emails. This way your main thread will remain clear.
