### ISSUE TITLE
problem compiling with "error: ‘nullptr’ was not declared in this scope"

### ISSUE THREAD

**Issue by gentooza** [bluetiger9/SmtpClient-for-Qt#74]
Hi!

I had to add to the qmake file the option:
```
CONFIG += c++11
```
For being able to compile it under GNU/Linux ubuntu 16.04, using -std=c++0x .

Nobody else had this problem?

cheers, and happy hacking!

**Comment by jigarshah088** [comment]
I think you can initialize your pointers with 0. that should also work.
