### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by ChrisBakerIKinema** [bluetiger9/SmtpClient-for-Qt#79]
Do I compile this as a lib or just include it all in my project as I get loads of compile errors.

**Comment by ChrisBakerIKinema** [comment]
Why is there no CMakeLists.txt ?

**Comment by bluetiger9** [comment]
The project used Qmake _(Qt-s build system)_, not Cmake. 

To build the project, you can either import the project in QT creator or build it from the command line:
```
$ qmake -project
$ qmake ./SMTPEmail.pro
$ make
```

Thanks,
Attila

**Comment by ChrisBakerIKinema** [comment]
Does Qt have it's own tool like the Visual Studio Command Prompt?

**Comment by ChrisBakerIKinema** [comment]
I have copied qmake locally and run it but my command prompt has not heard of make.

**Comment by esilvia** [comment]
Does using `nmake` instead of `make` work for you?
