### ISSUE TITLE
I can't embed images in a HTML mail.

### ISSUE THREAD

**Issue by ChrisBakerIKinema** [bluetiger9/SmtpClient-for-Qt#80]
I have tried the following example and I can't get it to work..

https://github.com/bluetiger9/SmtpClient-for-Qt/wiki/Examples#example3

I have a HTML email with 2 images in it. If I email to gmail the images do appear as attachments, if I email to my own outlook I don't even get that.

Here is my code...

	SmtpClient smtp("smtp.office365.com", 587, SmtpClient::TlsConnection);

	smtp.setUser(m_sender_email);
	smtp.setPassword(m_sender_email_password);
	smtp.setAuthMethod(SmtpClient::AuthLogin);

	MimeMessage message;
	
	message.setSender(new EmailAddress(m_sender_email, "Your Name"));
	message.addRecipient(new EmailAddress(dlg.lineEditClientMail->text(), "Recipient's Name"));
	message.setSubject(dlg.lineEditSubject->text());

	MimeHtml html;
	html.setHtml(dlg.textEditMessage->toHtml());
	
	QFile att(m_attach_file);
	MimeAttachment ma(&att);
	
	QFile image1("image001.png");
	QFile image2("image002.png");
	MimeInlineFile mai1(&image1);
	MimeInlineFile mai2(&image2);
		
	mai1.setContentId("image001");
	mai1.setContentType("image/png");

	mai2.setContentId("image002");
	mai2.setContentType("image/png");

	//	message.addPart(&text);
	message.addPart(&html);
	message.addPart(&mai1);
	message.addPart(&mai2);
	message.addPart(&ma);

	smtp.connectToHost();
	smtp.login();
	smtp.sendMail(message);
	smtp.quit();

**Comment by bluetiger9** [comment]
Hi @ChrisBakerIKinema,

Can you show me the HTML returned by:
```
dlg.textEditMessage->toHtml()
```
?

Does it look similar to the HTMl from the example:
```
    html.setHtml("<h1> Hello! </h1>"
                 "<h2> This is the first image </h2>"
                 "<img src='cid:image1' />"
                 "<h2> This is the second image </h2>"
                 "<img src='cid:image2' />");
```
?

Thanks,
Attila

**Comment by ChrisBakerIKinema** [comment]
I have to be careful here not to give away anything confidential.

It looks like HTML, it starts with

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><style type="text/css">
p,

**Comment by bluetiger9** [comment]
@ChrisBakerIKinema, ok. I understand this.

I would recommend to start with a simple HTML, with just a single `<img>` tag. Make sure the `src='cid:image001'` argument matches the content id set on the `MimeInlineFile`:
```
mai1.setContentId("image001");
```

**Comment by ChrisBakerIKinema** [comment]
Thanks for the help, I'll give that a go. My HTML is poor but I know Word can save in HTML format.

**Comment by ChrisBakerIKinema** [comment]
Also notice the line...

smtp.setAuthMethod(SmtpClient::AuthLogin);

I does not appear in your examples but on my computer it didn't work without it.

**Comment by ChrisBakerIKinema** [comment]
I tried a simple example and it did embed correctly thanks.
