### ISSUE TITLE
How to use this lib with read receipts

### ISSUE THREAD

**Issue by chrisghu** [bluetiger9/SmtpClient-for-Qt#81]
Hello,

First of all, many thanks for this great client. I have one question: is it possible to request read notifications for mails sent with this client? Read receipts or return receipts? I haven't found anything in the demos.

Thanks in advance. Best regards, Christian

**Comment by bluetiger9** [comment]
I don't know much about read receipts, but I guess they will need some custom mime headers. Customer headers are supported in `v2.0` of the library.
