### ISSUE TITLE
is it fast to instantiate a new SmptClient object each time you send a mail.?

### ISSUE THREAD

**Issue by opengpu** [bluetiger9/SmtpClient-for-Qt#84]
can i set a timeout ?
because it seems that i have to "instantiate a new SmptClient object each time you send a mail." in mainThread... and there is data updating at realtime very frequently at mainThread

**Comment by bluetiger9** [comment]
Instantiating a `new SmtpClient` should be fast. What could be slower is the actual email sending part. The time it takes to send the email depends on various factors like (internet connection, email server, etc.).

To mitigate this, you may want to use a dedicated thread for sending the emails. The library also supports setting connection, send and read timeouts.
