### ISSUE TITLE
new SmtpClient instead of SmtpClient smtp everytime send, will be faster?

### ISSUE THREAD

**Issue by opengpu** [bluetiger9/SmtpClient-for-Qt#88]
new SmtpClient instead of SmtpClient smtp everytime send, will be faster?

**Comment by bluetiger9** [comment]
Depends. The `sendEmail()` method can be called multiple times. So, you may save some time if you're sending many small emails. Just be aware that some email will not accept multiple emails on a single SMTP connection.
