### ISSUE TITLE
Is OpenSSL required?

### ISSUE THREAD

**Issue by eneshecan** [bluetiger9/SmtpClient-for-Qt#94]
Cannot connect to host when using TLS or SSL connection type on machines OpenSSL not deployed. Please add a requirement for that if dlls need to be deployed.

**Comment by bluetiger9** [comment]
Hi @eneshecan,

OpenSSL is required only if you want to use TLS / SSL connections.

You can pack the OpenSSL DLL-s along with your executable:
```
libeay32.dll
ssleay32.dll
```
*(see https://stackoverflow.com/a/22993271)*

This way, the TLS / SSL will work even if there is no OpenSSL installed on the given machine.

Thanks,
Attila

**Comment by eneshecan** [comment]
Thank you. I think it is better if you add this information to the README.
