### ISSUE TITLE
mimemultipart: bad default value for type

### ISSUE THREAD

**Issue by minutello** [bluetiger9/SmtpClient-for-Qt#96]
Since I'm always sending attachments, I had to change the `type` default value in `mimemultipart.h` to:
```
    /* [1] Constructors and Destructors */
    MimeMultiPart(const MultiPartType type = Mixed);
```
otherwise attachments will not be shown in all email clients, and the size of the attached files would be missing.

Maybe it's just a personal issue, but it's good to know if you're bugged with it.

**Comment by bluetiger9** [comment]
Good to know. Mime type can also be set with the `setMimeType()` method.
