### ISSUE TITLE
Display names are not double quoted

### ISSUE THREAD

**Issue by Steeven9** [bluetiger9/SmtpClient-for-Qt#98]
When using a display name (either as sender or recipient) with some special characters, like an @, the smtp server may run into some parsing problems. In my case I was setting the email address as the display name of the recipient and it was being parsed as `name@ <"domain.com name"@domain.com>` instead of `name@domain.com <name@domain.com>`.

The solution would be enclosing the display name in escaped double quotes (`\"`) if some special characters are detected in the display name (see the relevant RFC specs for the details).

**Comment by bluetiger9** [comment]
Hi! 

I think you should set a header encoding _(Quoted Printable, or Base64)_ on the `MimeMessage`.

It should look something like:
```
message.setHeaderEncoding(MimePart::QuotedPrintable)
```

Let me know if this works!

Thanks,
Attila

**Comment by Steeven9** [comment]
Hi, 
my solution was to simply remove the recipient name and go with the address only (which fixed it). But for sake of completeness, I tried your solution and it yields this: `=?utf-8?Q?name@ <"domain.com?= name"@domain.com>` (again instead of `name@domain.com <name@domain.com>`)
